//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VxEventInjector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VxEventInjector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully configure the current event agent before proceeding.
        /// </summary>
        public static string ConfigureAgentBeforeProceeding {
            get {
                return ResourceManager.GetString("ConfigureAgentBeforeProceeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to communicate with the event injector service, check that it is started and try again.
        /// </summary>
        public static string InjectorSvcNotStartedMsg {
            get {
                return ResourceManager.GetString("InjectorSvcNotStartedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more event agents before continuing.
        /// </summary>
        public static string MustSelectEventAgent {
            get {
                return ResourceManager.GetString("MustSelectEventAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceeding will delete the existing configuration and use this one instead, proceed?.
        /// </summary>
        public static string ProceedWithConfigurationSave {
            get {
                return ResourceManager.GetString("ProceedWithConfigurationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionAgentConfigVx.
        /// </summary>
        public static string RegionAgentConfig {
            get {
                return ResourceManager.GetString("RegionAgentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionConfigMainVx.
        /// </summary>
        public static string RegionConfigMain {
            get {
                return ResourceManager.GetString("RegionConfigMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionShellVx.
        /// </summary>
        public static string RegionShell {
            get {
                return ResourceManager.GetString("RegionShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAgentConfigVx.
        /// </summary>
        public static string ViewAgentConfig {
            get {
                return ResourceManager.GetString("ViewAgentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAgentSelectorVx.
        /// </summary>
        public static string ViewAgentSelector {
            get {
                return ResourceManager.GetString("ViewAgentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewCompleteVx.
        /// </summary>
        public static string ViewComplete {
            get {
                return ResourceManager.GetString("ViewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewConfigPageVx.
        /// </summary>
        public static string ViewConfigPage {
            get {
                return ResourceManager.GetString("ViewConfigPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewProcessAgentsVx.
        /// </summary>
        public static string ViewProcessAgents {
            get {
                return ResourceManager.GetString("ViewProcessAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewVxLoginVx.
        /// </summary>
        public static string ViewVxLogin {
            get {
                return ResourceManager.GetString("ViewVxLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login to VideoXpert, check your credentials or network settings and try again.
        /// </summary>
        public static string VxLoginFailMsg {
            get {
                return ResourceManager.GetString("VxLoginFailMsg", resourceCulture);
            }
        }
    }
}
